---
title: "Extra"
author: "Dan Birman"
date: "Tuesday, October 21, 2014"
output: html_document
---

###B1

Prep work
```{r}
st = data.frame(SSx = 2.52, SSy = 780, sum_x = 24, sum_y = 870, sum_xy = 349.25, n=64, xbar = .375, ybar =13.6)

# st$SPxy = sum(x*y) - xbar*sum(y) - ybar*sum(x) + n*xbar*ybar
st$SPxy = st$sum_xy - st$xbar*st$sum_y - st$ybar*st$sum_x+st$n*st$xbar*st$ybar
```

Calculate r and p(r)
```{r}
r = st$SPxy / sqrt(st$SSy * st$SSx)
t_r = r * sqrt((st$n-2)/(1-r^2))
p_r = pt(t_r,st$n-2,lower.tail=F)
```

The correlation was found to be $r = `r p(r)`, p < .001$.

###B2

```{r}
b = st$SPxy / st$SSx
a = st$ybar - b*st$xbar
```

The regression equation was found to be $y = `r p(a)` + `r p(b)`*x$.

###B3

```{r}
var_y = st$SSy/(st$n-1)
s_y = sqrt(var_y)

se_y = s_y / sqrt(st$n)

ci_y90 = c(st$ybar - se_y * 1.64,st$ybar + se_y*1.64)
```

The confidence interval for $\mu_y$ was found to be $`r p(ci_y90)`$

###B4

```{r}
x = .18
yv = a + b*x
```

$Pred. Death Rate (`r p(x)`) = `r p(yv)`$. This is below the 90% confidence interval range, so there hospital is in the lowest 5% of hospitals in terms of risk of death.








ALSO SHOW THIS (Relevant to Quiz 1):
```{r}
data = read.csv("http://web.stanford.edu/class/psych252/_downloads/acupuncture.csv")
data$otcF = factor(data$otc,levels=c(1,2),labels=c("Yes","No"))
rs9 = glm(otcF ~ relief,data,family="binomial")
ggplot(data,(aes(relief,otc-1))) + 
  geom_point() + 
  # If X Categorical add geom_jitter(position=position_jitter(width=?,height=?))
  geom_smooth(method="glm",family="binomial") + 
  ggtitle("Sigmoid Curve Fit for OTC Use vs. Back Pain Relief")
```
