---
title: "Untitled"
author: "Dan Birman"
date: "Tuesday, March 31, 2015"
output: html_document
---

```{r}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

```{r}
library(ggplot2)
```

```{r}

c = seq(0,100)

rmax = 1
n = 5
c50 = 50
b = .25

y1 = rmax*c^n/(c^n+c50^n) + b # con cued v1
y2 = rmax*c^n/(c^n+c50^n) + b + .05
n = 1
rmax = .5
b = .5
y3 = rmax*c^n/(c^n+c50^n) + b # coh cued v1
y4 = rmax*c^n/(c^n+c50^n) + b + .05

rmax = 1
n = 3
b = .45
y5 = rmax*c^n/(c^n+c50^n) + b # con cued v1
y6 = rmax*c^n/(c^n+c50^n) + b + .05

b = .2
n = 5
y7 = (rmax-.3)*c^n/(c^n+(c50)^n) + b
y8 = (rmax-.3)*c^n/(c^n+(c50)^n) + b


d = data.frame(c=c,y1=y1,y2=y2,y3=y3,y4=y4,y5=y5,y6=y6,y7=y7,y8=y8)


```

```{r}
b = .5

p1 = ggplot(d) +
  geom_line(aes(c,y1),color='black',size=2) +
  geom_line(aes(c,y2),color='grey',size=2) +
  geom_hline(aes(yintercept=b),color='red',size=2) +
  geom_hline(aes(yintercept=b+.01),color='pink',size=2) +
  theme_bw() +
  scale_x_continuous(breaks=c(0,50,100)) +
  scale_y_continuous(breaks=c()) +
  xlab('Feature Intensity (%)') +
  ylab('Response Amplitude') +
  theme(text = element_text(size=20))

p2 = ggplot(d) +
  geom_line(aes(c,y5),color='black',size=2) + 
  geom_line(aes(c,y6),color='grey',size=2) + 
  geom_line(aes(c,y7),color='turquoise2',size=2) + 
  geom_line(aes(c,y8),color='turquoise1',size=2) + 
  theme_bw() +
  scale_x_continuous(breaks=c(0,50,100)) +
  scale_y_continuous(breaks=c()) +
  xlab('Feature Intensity (%)') +
  ylab('Response Amplitude') +
    theme(text = element_text(size=20))
```

```{r}
multiplot(p1,p2,layout=matrix(c(1,2), nrow=1, byrow=TRUE))
```


